booking:
    pattern:  /
    defaults: { _controller: "TNEOperatorBundle:Customer:index" }

booking_show:
    pattern:  /{id}/show
    defaults: { _controller: "TNEOperatorBundle:Customer:show" }

booking_new:
    pattern:  /new
    defaults: { _controller: "TNEOperatorBundle:Customer:new" }

booking_create:
    pattern:  /create
    defaults: { _controller: "TNEOperatorBundle:Customer:create" }
    requirements: { _method: post }

booking_edit:
    pattern:  /{id}/edit
    defaults: { _controller: "TNEOperatorBundle:Customer:edit" }

booking_update:
    pattern:  /{id}/update
    defaults: { _controller: "TNEOperatorBundle:Customer:update" }
    requirements: { _method: post }

booking_delete:
    pattern:  /{id}/delete
    defaults: { _controller: "TNEOperatorBundle:Customer:delete" }
    requirements: { _method: post }

booking_cart:
    pattern:  /cart
    defaults: { _controller: "TNEOperatorBundle:Customer:cart" }

booking_add_to_cart:
    pattern:  /addToCart
    defaults: { _controller: "TNEOperatorBundle:Customer:addToCart" }

booking_remove_from_cart:
    pattern:  /removeFromCart/{id}
    defaults: { _controller: "TNEOperatorBundle:Customer:removeFromCart" }

booking_order_confirmation:
    pattern:  /confimation/{id}
    defaults: { _controller: "TNEOperatorBundle:Customer:confirmation" }

