parameters:
    #Custom map renderer
    vich_geographical.map_renderer.google: TNE\OperatorBundle\Map\Renderer\GoogleMapRenderer

services:
  tneoperator.form.type.map:
      class: TNE\OperatorBundle\Form\Type\MapType
  #    arguments:
  #        - "%genders%"
      tags:
          - { name: form.type, alias: map }

  tneoperator.admin.owner.filter:
      class: TNE\OperatorBundle\Admin\Filter\OwnerFilter
      arguments: ["@security.context", "id"]
      tags:
          - { name: filter.type, alias: owner.filter }