#
# more information can be found here http://sonata-project.org/bundles/page
#
symfony_cmf_routing_extra:
    chain:
        routers_by_id:
            # enable the DynamicRouter with high priority to allow overwriting configured routes with content
            #symfony_cmf_routing_extra.dynamic_router: 200
            # enable the symfony default router with a lower priority
            sonata.page.router: 150
            router.default: 100

sonata_page:
    multisite:             host
    use_streamed_response: false # set the value to false in debug mode or if the reverse proxy does not handle streamed response
    ignore_route_patterns:
        - (.*)admin(.*)     # ignore admin route, ie route containing 'admin'
        - ^_(.*)            # ignore symfony routes

    ignore_routes:
        - sonata_page_esi_cache
        - sonata_page_ssi_cache
        - sonata_page_js_sync_cache
        - sonata_page_js_async_cache
        - sonata_cache_esi
        - sonata_cache_ssi
        - sonata_cache_js_async
        - sonata_cache_js_sync
        - sonata_cache_apc
        - tne_operator_listing_search
        - tne_operator_details
        - tne_operator_listing_list
        - tne_operator_listing_destinations_list
        - tne_operator_listing_attractions_list
        - tne_operator_listing_events_list
        - tne_operator_listing_classifications_list
        - fullcalendar_loader
        - fos_js_routing_js
        - tne_room_calender
        - tne_operators_add_to_cart

    ignore_uri_patterns:
        - admin(.*)         # ignore admin route, ie route containing 'admin'
        - /booking/*

    cache_invalidation:
        service:  sonata.page.cache.invalidation.simple
        recorder: sonata.page.cache.recorder
        classes:
            "Application\Sonata\PageBundle\Entity\Block": getId

    default_template: default
    templates:
#        default: { path: 'ApplicationSonataPageBundle::layout.html.twig', name: 'default' }
#        home: { path: 'ApplicationSonataPageBundle::home_layout.html.twig', name: 'Home Template' }
        home-rutherglen: { path: 'ApplicationSonataPageBundle::rutherglen_home_layout.html.twig', name: 'Rutherglen Home Template' }
#        gallery: { path: 'ApplicationSonataPageBundle::gallery_layout.html.twig', name: 'gallery' }
#        map: { path: 'ApplicationSonataPageBundle::layout_map.html.twig', name: 'map' }
        content: { path: 'ApplicationSonataPageBundle::about.html.twig', name: 'Content Template' }

    page_defaults:
        homepage: {decorate: true, enabled: true}

    caches:
        esi:
            token:    add an unique token here # default is a random value
            servers:
                - varnishadm -T 127.0.0.1:2000 {{ COMMAND }} "{{ EXPRESSION }}"

        ssi:
            token:    add an unique token here # default is a random value

    catch_exceptions:
        not_found: [404]    # render 404 page with "not_found" key (name generated: _page_internal_error_{key})
        fatal:     [500]    # so you can use the same page for different http errors or specify specific page for each error


# Enable Doctrine to map the provided entities
doctrine:
    orm:
        entity_managers:
            default:
                mappings:
                    ApplicationSonataPageBundle: ~
                    SonataPageBundle: ~