<?php

namespace TNE\OperatorBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * AttractionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AttractionRepository extends EntityRepository
{
}
