<?php

namespace TNE\OperatorBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * OperatorMediaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class OperatorMediaRepository extends EntityRepository
{
}
