parameters:
    #Site Admin Controller
    sonata.page.admin.site.class:      Application\Sonata\PageBundle\Admin\SiteAdmin
    #Page Admin Class
    sonata.page.admin.page.class:      Application\Sonata\PageBundle\Admin\PageAdmin
    #Page Admin Controller
    sonata.page.admin.page.controller: ApplicationSonataPageBundle:PageAdmin
    #Template rendering service for default type pages
    sonata.page.service.default.class: Application\Sonata\PageBundle\Page\Service\DefaultPageService
    #snapshot manager
    sonata.page.manager.snapshot.class: Application\Sonata\PageBundle\Entity\SnapshotManager
    #CMS Snapshot Manager
    sonata.page.cms_manager.snapshot.class: Application\Sonata\PageBundle\CmsManager\CmsSnapshotManager
    
#    sonata.media.manager.media: Application\Sonata\PageBundle\Block\MediaManagerInterface
    
    sonata.media.manager.media.class: Application\Sonata\PageBundle\Block\MediaManager
    
services: 
      
    sonata.block.service.taggedmedia:
        class:        Application\Sonata\PageBundle\Block\TaggedMediaBlockService
        arguments:    ['sonata.block.service.taggedmedia', "@templating", "@service_container", "@sonata.media.manager.media"]
        tags:
            -  { name: sonata.block, agile_content_sidebar_title: "RichText", agile_content_sidebar_class: "sidebar_block ui-draggable" , agile_content_sidebar_data_template: "text-block-template" }        
            
            
#Application\Sonata\PageBundle\Block\MediaManagerInterface, instance of Sonata\MediaBundle\Entity\MediaManager