parameters:
    sonata.page.admin.site.class:      Application\Sonata\PageBundle\Admin\SiteAdmin
    sonata.page.admin.page.class:      Application\Sonata\PageBundle\Admin\PageAdmin
    sonata.page.admin.page.controller: ApplicationSonataPageBundle:PageAdmin