<?php
/**
 * This file is part of the <name> project.
 *
 * (c) <yourname> <youremail>
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */

namespace Application\Sonata\PageBundle\Entity;

use Sonata\PageBundle\Entity\BaseSite as BaseSite;

/**
 * This file has been generated by the Sonata EasyExtends bundle ( http://sonata-project.org/easy-extends )
 *
 * References :
 *   working with object : http://www.doctrine-project.org/projects/orm/2.0/docs/reference/working-with-objects/en
 *
 * @author <yourname> <youremail>
 */
class Site extends BaseSite
{

    /**
     * @var integer $id
     */
    protected $id;
    
    /**
     *
     * @var type string
     */
    private $context;


    private $gacode;

    /**
     * Get id
     *
     * @return integer $id
     */
    public function getId()
    {
        return $this->id;
    }
    
    public function getContext()
    {
        return $this->context;
    }
    
    public function setContext($context)
    {
        $this->context = $context;
    }

    /**
     * @param mixed $gacode
     */
    public function setGacode($gacode)
    {
        $this->gacode = $gacode;
    }

    /**
     * @return mixed
     */
    public function getGacode()
    {
        return $this->gacode;
    }



}